CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS organization_health_snapshots (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, score INTEGER, dimensions JSONB NOT NULL DEFAULT '{}', availability JSONB NOT NULL DEFAULT '{}', captured_at TIMESTAMPTZ NOT NULL, created_by TEXT);
CREATE INDEX IF NOT EXISTS idx_org_health_snapshots_scope ON organization_health_snapshots(organization_id, captured_at DESC);
CREATE TABLE IF NOT EXISTS organization_risk_signals (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, type TEXT NOT NULL, severity TEXT NOT NULL, title TEXT NOT NULL, reason TEXT, evidence JSONB NOT NULL DEFAULT '[]', owner_id TEXT, status TEXT NOT NULL DEFAULT 'open', detected_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_org_risks_scope ON organization_risk_signals(organization_id, status, severity);
CREATE TABLE IF NOT EXISTS organization_actions (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, title TEXT NOT NULL, reason TEXT, evidence JSONB NOT NULL DEFAULT '[]', source_type TEXT NOT NULL, source_id TEXT, owner_id TEXT, priority TEXT NOT NULL, due_date TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'open', created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_org_actions_scope ON organization_actions(organization_id, status, priority, due_date);
CREATE TABLE IF NOT EXISTS organization_activity_events (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, type TEXT NOT NULL, resource_type TEXT, resource_id TEXT, message TEXT NOT NULL, actor_id TEXT, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_org_activity_scope ON organization_activity_events(organization_id, created_at DESC);
CREATE TABLE IF NOT EXISTS organization_kpi_definitions (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, name TEXT NOT NULL, definition TEXT, unit TEXT NOT NULL, target NUMERIC, frequency TEXT NOT NULL, owner_id TEXT, visibility TEXT NOT NULL, created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS organization_kpi_values (id TEXT PRIMARY KEY, definition_id TEXT NOT NULL REFERENCES organization_kpi_definitions(id) ON DELETE CASCADE, organization_id TEXT NOT NULL, value NUMERIC NOT NULL, source TEXT NOT NULL, period_start TIMESTAMPTZ, period_end TIMESTAMPTZ, recorded_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_org_kpi_values_scope ON organization_kpi_values(organization_id, definition_id, period_end DESC);
CREATE TABLE IF NOT EXISTS organization_audit_events (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, actor_id TEXT NOT NULL, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT NOT NULL, previous_state JSONB, new_state JSONB, metadata JSONB NOT NULL DEFAULT '{}', previous_hash TEXT NOT NULL, event_hash TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_org_audit_scope ON organization_audit_events(organization_id, created_at DESC);
CREATE TABLE IF NOT EXISTS organization_report_schedules (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, report_type TEXT NOT NULL, frequency TEXT NOT NULL, recipients JSONB NOT NULL DEFAULT '[]', filters JSONB NOT NULL DEFAULT '{}', active BOOLEAN NOT NULL DEFAULT true, created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS organization_partners (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, programs JSONB NOT NULL DEFAULT '[]', notes TEXT, created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS organization_cohorts (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, program_id TEXT, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'planned', start_date TIMESTAMPTZ, end_date TIMESTAMPTZ, created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS organization_resources (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT, url TEXT, kind TEXT, visibility TEXT NOT NULL DEFAULT 'organization', created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS organization_recommendations (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, risk_id TEXT, recommendation TEXT NOT NULL, why TEXT, evidence JSONB NOT NULL DEFAULT '[]', confidence TEXT, priority TEXT, expected_outcome TEXT, suggested_owner_role TEXT, status TEXT NOT NULL DEFAULT 'active', deterministic BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);

CREATE OR REPLACE FUNCTION organization_audit_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'organization audit events are append-only'; END $$;
DROP TRIGGER IF EXISTS trg_organization_audit_immutable ON organization_audit_events;
CREATE TRIGGER trg_organization_audit_immutable BEFORE UPDATE OR DELETE ON organization_audit_events FOR EACH ROW EXECUTE FUNCTION organization_audit_immutable();
REVOKE UPDATE, DELETE ON organization_audit_events FROM PUBLIC;
CREATE OR REPLACE FUNCTION techit_org_member(target_org TEXT) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM trust_organization_memberships m WHERE m.organization_id = target_org AND m.user_id = NULLIF(current_setting('app.user_id', true), '') AND m.status = 'active') OR target_org = NULLIF(current_setting('app.user_id', true), '') $$;
ALTER TABLE organization_health_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_risk_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_kpi_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_kpi_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_report_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_cohorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_recommendations ENABLE ROW LEVEL SECURITY;
DO $$ DECLARE table_name TEXT; BEGIN FOREACH table_name IN ARRAY ARRAY['organization_health_snapshots','organization_risk_signals','organization_actions','organization_activity_events','organization_kpi_definitions','organization_kpi_values','organization_report_schedules','organization_partners','organization_cohorts','organization_resources','organization_recommendations'] LOOP EXECUTE format('DROP POLICY IF EXISTS organization_scope_policy ON %I', table_name); EXECUTE format('CREATE POLICY organization_scope_policy ON %I USING (techit_org_member(organization_id))', table_name); END LOOP; END $$;
DROP POLICY IF EXISTS organization_audit_scope_policy ON organization_audit_events;
CREATE POLICY organization_audit_scope_policy ON organization_audit_events USING (techit_org_member(organization_id));
