CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS support_cases (id TEXT PRIMARY KEY, case_number TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL, user_role TEXT NOT NULL, category TEXT NOT NULL, subcategory TEXT, subject TEXT NOT NULL, description TEXT NOT NULL, priority TEXT NOT NULL, severity TEXT NOT NULL, status TEXT NOT NULL, assigned_admin_id TEXT, assigned_team TEXT, escalation_level INTEGER NOT NULL DEFAULT 1, escalation_status TEXT NOT NULL DEFAULT 'none', first_response_due_at TIMESTAMPTZ, resolution_due_at TIMESTAMPTZ, first_responded_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ, closed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_messages (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES support_cases(id), sender_type TEXT NOT NULL, sender_id TEXT NOT NULL, message TEXT NOT NULL, is_internal BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_events (id TEXT PRIMARY KEY, case_id TEXT, event_type TEXT NOT NULL, actor_id TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_audit_logs (id TEXT PRIMARY KEY, case_id TEXT, action TEXT NOT NULL, actor_id TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_attachments (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES support_cases(id), name TEXT NOT NULL, content_type TEXT NOT NULL, size_bytes BIGINT NOT NULL, object_key TEXT, status TEXT NOT NULL, uploaded_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_feedback (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES support_cases(id), user_id TEXT NOT NULL, rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5), resolution_status TEXT, comment TEXT, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_locks (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES support_cases(id), admin_id TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_sla_policies (id TEXT PRIMARY KEY, priority TEXT NOT NULL, first_response_minutes INTEGER NOT NULL, resolution_minutes INTEGER NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, updated_by TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_settings (key TEXT PRIMARY KEY, value JSONB NOT NULL, updated_by TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_categories (id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, label TEXT NOT NULL, exempt_from_cooldown BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE, updated_by TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_teams (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, level INTEGER NOT NULL DEFAULT 1, categories JSONB NOT NULL DEFAULT '[]', active BOOLEAN NOT NULL DEFAULT TRUE, updated_by TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_knowledge_base (id TEXT PRIMARY KEY, title TEXT NOT NULL, problem TEXT, solution TEXT NOT NULL, category TEXT NOT NULL, escalation_conditions JSONB NOT NULL DEFAULT '[]', active BOOLEAN NOT NULL DEFAULT TRUE, updated_by TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, content TEXT NOT NULL, category TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, updated_by TEXT, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_incidents (id TEXT PRIMARY KEY, category TEXT NOT NULL, case_ids JSONB NOT NULL DEFAULT '[]', count INTEGER NOT NULL, status TEXT NOT NULL, detected_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS support_intelligence_signals (id TEXT PRIMARY KEY, source TEXT NOT NULL, domain TEXT NOT NULL, type TEXT NOT NULL, category TEXT, evidence_count INTEGER, reference_ids JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_support_cases_queue ON support_cases(status, priority, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_cases_user ON support_cases(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_messages_case ON support_messages(case_id, created_at);
CREATE OR REPLACE FUNCTION support_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'support evidence is append-only'; END $$;
DROP TRIGGER IF EXISTS trg_support_messages_immutable ON support_messages;
CREATE TRIGGER trg_support_messages_immutable BEFORE UPDATE OR DELETE ON support_messages FOR EACH ROW EXECUTE FUNCTION support_append_only();
DROP TRIGGER IF EXISTS trg_support_events_immutable ON support_events;
CREATE TRIGGER trg_support_events_immutable BEFORE UPDATE OR DELETE ON support_events FOR EACH ROW EXECUTE FUNCTION support_append_only();
DROP TRIGGER IF EXISTS trg_support_audit_immutable ON support_audit_logs;
CREATE TRIGGER trg_support_audit_immutable BEFORE UPDATE OR DELETE ON support_audit_logs FOR EACH ROW EXECUTE FUNCTION support_append_only();
REVOKE UPDATE, DELETE ON support_messages, support_events, support_audit_logs FROM PUBLIC;
CREATE OR REPLACE FUNCTION techit_support_admin() RETURNS BOOLEAN LANGUAGE sql STABLE AS $$ SELECT current_setting('app.is_admin', true) = 'true' $$;
CREATE OR REPLACE FUNCTION techit_support_user(target_user TEXT) RETURNS BOOLEAN LANGUAGE sql STABLE AS $$ SELECT techit_support_admin() OR target_user = NULLIF(current_setting('app.user_id', true), '') $$;
ALTER TABLE support_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_sla_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_intelligence_signals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS support_cases_scope ON support_cases;
CREATE POLICY support_cases_scope ON support_cases USING (techit_support_user(user_id));
DROP POLICY IF EXISTS support_messages_scope ON support_messages;
CREATE POLICY support_messages_scope ON support_messages USING (techit_support_admin() OR EXISTS (SELECT 1 FROM support_cases c WHERE c.id = case_id AND techit_support_user(c.user_id)));
DROP POLICY IF EXISTS support_events_scope ON support_events;
CREATE POLICY support_events_scope ON support_events USING (techit_support_admin() OR EXISTS (SELECT 1 FROM support_cases c WHERE c.id = case_id AND techit_support_user(c.user_id)));
DROP POLICY IF EXISTS support_audit_scope ON support_audit_logs;
CREATE POLICY support_audit_scope ON support_audit_logs USING (techit_support_admin());
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['support_attachments','support_feedback','support_locks'] LOOP EXECUTE format('DROP POLICY IF EXISTS support_case_child_scope ON %I', t); EXECUTE format('CREATE POLICY support_case_child_scope ON %I USING (techit_support_admin() OR EXISTS (SELECT 1 FROM support_cases c WHERE c.id = case_id AND techit_support_user(c.user_id)))', t); END LOOP; END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['support_sla_policies','support_settings','support_categories','support_teams','support_knowledge_base','support_templates','support_incidents','support_intelligence_signals'] LOOP EXECUTE format('DROP POLICY IF EXISTS support_admin_scope ON %I', t); EXECUTE format('CREATE POLICY support_admin_scope ON %I USING (techit_support_admin())', t); END LOOP; END $$;
