CREATE TABLE IF NOT EXISTS core_wallet_accounts (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE,balance NUMERIC NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'USD',payload JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS core_credit_ledger (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,delta_credits NUMERIC NOT NULL,type TEXT NOT NULL,payment_intent_id TEXT,idempotency_key TEXT UNIQUE,payload JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS core_usage_reservations (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,reserved_credits NUMERIC NOT NULL DEFAULT 0,status TEXT NOT NULL,idempotency_key TEXT UNIQUE,payload JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS core_payment_intents (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,amount NUMERIC NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'USD',credits NUMERIC NOT NULL DEFAULT 0,status TEXT NOT NULL,idempotency_key TEXT,payload JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(user_id,idempotency_key));
CREATE TABLE IF NOT EXISTS core_subscriptions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,plan_id TEXT,status TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS core_billing_webhook_events (id TEXT PRIMARY KEY,provider TEXT NOT NULL,event_id TEXT NOT NULL,type TEXT,status TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL,UNIQUE(provider,event_id));
CREATE INDEX IF NOT EXISTS idx_core_credit_ledger_user_time ON core_credit_ledger(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_core_usage_reservations_user_status ON core_usage_reservations(user_id,status);
CREATE INDEX IF NOT EXISTS idx_core_payment_intents_user_status ON core_payment_intents(user_id,status,created_at DESC);
