import { createHash, randomBytes } from 'node:crypto'
import { createId, nowIso } from '../utils/api.js'
import { readDb, updateDb } from '../config/database.js'
import { createPrivateUpload, finalizePrivateUpload, privateDownloadUrl } from './evidenceStorageService.js'

const collection = (db, name) => { if (!Array.isArray(db[name])) db[name] = []; return db[name] }
const text = value => typeof value === 'string' ? value.trim() : value
const sha = value => createHash('sha256').update(String(value || '')).digest('hex')
const hashToken = value => sha(value)
const now = () => nowIso()
const roles = new Set(['owner', 'reviewer', 'ic_member', 'legal', 'finance', 'read_only', 'diligence_owner'])
const checklistStatuses = new Set(['not_started', 'requested', 'submitted', 'under_review', 'accepted', 'needs_clarification', 'waived'])
const visibility = new Set(['founder_visible', 'investor_internal', 'participants'])

function dealFor(db, dealId) { return collection(db, 'dealRooms').find(row => row.id === dealId && row.status !== 'archived') || null }
function memberFor(db, dealId, userId) { return collection(db, 'dealRoomParticipants').find(row => row.dealId === dealId && row.userId === userId && row.status !== 'revoked') || null }
function templateFor(db, deal) { return collection(db, 'ndaTemplates').find(row => row.id === deal?.ndaTemplateId && row.active !== false) || null }
function ndaFor(db, deal, userId) { const t = templateFor(db, deal); return Boolean(t && collection(db, 'ndaSignatures').some(row => row.dealId === deal.id && row.userId === userId && row.templateVersion === t.version && row.accepted === true && !row.revokedAt)) }
function authorize(db, userId, dealId, { nda = false, investorOnly = false, allowedRoles = null } = {}) {
  const deal = dealFor(db, dealId); const member = deal && memberFor(db, dealId, userId)
  if (!deal || !member) return { ok: false, error: 'deal_room_not_found' }
  if (investorOnly && !['owner', 'reviewer', 'ic_member', 'legal', 'finance', 'read_only'].includes(member.role)) return { ok: false, error: 'investor_permission_required' }
  if (allowedRoles && !allowedRoles.includes(member.role)) return { ok: false, error: 'investor_permission_required' }
  if (nda && ['owner', 'reviewer', 'ic_member', 'legal', 'finance', 'read_only'].includes(member.role) && !ndaFor(db, deal, deal.investorId)) return { ok: false, error: 'nda_required' }
  return { ok: true, deal, member }
}
function audit(db, dealId, actorId, action, metadata = {}) {
  const events = collection(db, 'dealAuditEvents'); const previous = events.filter(row => row.dealId === dealId).slice(-1)[0]
  const createdAt = now(); const sourceDataHash = sha(JSON.stringify(metadata)); const prevHash = previous?.eventHash || 'GENESIS'
  const eventHash = sha(`${prevHash}|${dealId}|${actorId || ''}|${action}|${sourceDataHash}|${createdAt}`)
  const event = { id: createId('deal_audit'), dealId, actorId, action, metadata, sourceDataHash, prevHash, eventHash, createdAt }
  events.push(event); return event
}
function notification(db, userId, type, dealId, metadata = {}) {
  if (!userId) return
  collection(db, 'notifications').push({ id: createId('notif'), userId, type, content: `Deal Room update: ${type.replaceAll('_', ' ')}`, linkTo: `/investors/deals/${dealId}`, metadata: { dealId, ...metadata }, read: false, createdAt: now() })
}
function safeDocument(row) { const { objectKey, sourceUrl, ...safe } = row; return { ...safe, hasPrivateObject: Boolean(objectKey), hasExternalSource: Boolean(sourceUrl) } }

export function createDealFolder(userId, dealId, body = {}) {
  return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth
    const name = text(body.name); if (!name) return { ok: false, error: 'folder_name_required' }
    const folder = { id: createId('data_room_folder'), dealId, name, category: text(body.category) || 'Other', createdBy: userId, createdAt: now(), updatedAt: now() }
    collection(db, 'dataRoomFolders').push(folder); audit(db, dealId, userId, 'data_room_folder_created', { folderId: folder.id }); return { ok: true, folder }
  })
}

export function listDealFolders(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; return { ok: true, folders: collection(db, 'dataRoomFolders').filter(row => row.dealId === dealId) } }

export function createDocumentRequest(userId, dealId, body = {}) {
  return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const title = text(body.title); if (!title) return { ok: false, error: 'document_title_required' }
    const request = { id: createId('evidence_request'), dealId, title, category: text(body.category) || 'Other', required: body.required !== false, visibility: visibility.has(body.visibility) ? body.visibility : 'participants', ownerId: body.ownerId || auth.deal.founderId || null, reviewerId: body.reviewerId || null, status: 'requested', priority: body.priority || 'standard', dueDate: body.dueDate || null, createdBy: userId, requestedAt: now(), createdAt: now(), updatedAt: now() }
    collection(db, 'diligenceEvidenceLinks').push(request); audit(db, dealId, userId, 'diligence_request_created', { requestId: request.id }); notification(db, request.ownerId, 'diligence_request_created', dealId, { requestId: request.id }); return { ok: true, request }
  })
}

export function registerDealDocument(userId, dealId, body = {}) {
  return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const name = text(body.name); const contentType = text(body.contentType) || 'application/pdf'; if (!name) return { ok: false, error: 'document_name_required' }
    const folder = body.folderId ? collection(db, 'dataRoomFolders').find(row => row.id === body.folderId && row.dealId === dealId) : null; if (body.folderId && !folder) return { ok: false, error: 'folder_not_found' }
    const existing = body.documentId ? collection(db, 'dataRoomDocuments').find(row => row.id === body.documentId && row.dealId === dealId && !row.revokedAt) : null
    if (body.documentId && !existing) return { ok: false, error: 'document_not_found' }
    const document = existing || { id: createId('data_room_document'), dealId, folderId: folder?.id || null, name, category: text(body.category) || folder?.category || 'Other', contentType, sizeBytes: Number(body.sizeBytes) || 0, visibility: visibility.has(body.visibility) ? body.visibility : 'participants', allowPreview: body.allowPreview !== false, allowDownload: body.allowDownload !== false, watermarkRequired: body.watermarkRequired === true, status: 'upload_pending', malwareStatus: 'pending', expiresAt: body.expiresAt || null, revokedAt: null, createdBy: userId, createdAt: now(), updatedAt: now() }
    if (!existing) collection(db, 'dataRoomDocuments').push(document)
    else Object.assign(document, { name, contentType, sizeBytes: Number(body.sizeBytes) || 0, status: 'upload_pending', malwareStatus: 'pending', updatedAt: now() })
    const nextVersion = collection(db, 'dataRoomDocumentVersions').filter(row => row.documentId === document.id).reduce((max, row) => Math.max(max, Number(row.version) || 0), 0) + 1
    const version = { id: createId('data_room_version'), documentId: document.id, version: nextVersion, checksum: null, objectKey: null, sourceUrl: null, status: 'upload_pending', uploadedBy: userId, createdAt: now() }; collection(db, 'dataRoomDocumentVersions').push(version)
    const upload = createPrivateUpload({ namespace: `deals/${dealId}`, ownerId: userId, objectId: document.id, contentType, sizeBytes: document.sizeBytes })
    if (upload.ok) Object.assign(version, { objectKey: upload.objectKey })
    else if (body.sourceUrl && /^https?:\/\//i.test(body.sourceUrl)) Object.assign(version, { sourceUrl: body.sourceUrl, status: 'linked_pending' })
    else return { ok: false, error: upload.error || 'private_storage_not_configured' }
    audit(db, dealId, userId, 'document_upload_started', { documentId: document.id, version: nextVersion }); return { ok: true, document: safeDocument(document), version: { ...version, objectKey: undefined, sourceUrl: undefined }, upload: upload.ok ? { uploadUrl: upload.uploadUrl, requiredHeaders: upload.requiredHeaders } : null }
  })
}

export async function finalizeDealDocument(userId, dealId, documentId) {
  const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth
  const document = collection(db, 'dataRoomDocuments').find(row => row.id === documentId && row.dealId === dealId); const version = collection(db, 'dataRoomDocumentVersions').filter(row => row.documentId === documentId && row.status !== 'available').sort((a, b) => b.version - a.version)[0]
  if (!document || !version) return { ok: false, error: 'document_not_found' }
  if (version.sourceUrl) return updateDb(state => { const row = state.dataRoomDocuments.find(item => item.id === documentId); const v = state.dataRoomDocumentVersions.find(item => item.id === version.id); row.status = 'available'; row.malwareStatus = 'not_applicable_external'; row.updatedAt = now(); v.status = 'available'; audit(state, dealId, userId, 'document_uploaded', { documentId, source: 'external_link' }); return { ok: true, document: safeDocument(row), version: v } })
  const result = await finalizePrivateUpload({ ownerId: userId, objectId: documentId, objectKey: version.objectKey, contentType: document.contentType, expectedSizeBytes: document.sizeBytes })
  if (!result.ok) return result
  return updateDb(state => { const row = state.dataRoomDocuments.find(item => item.id === documentId); const v = state.dataRoomDocumentVersions.find(item => item.id === version.id); Object.assign(row, { status: 'available', malwareStatus: 'clean', checksum: result.sha256, updatedAt: now() }); Object.assign(v, { status: 'available', checksum: result.sha256, scan: result.scan, createdAt: v.createdAt }); audit(state, dealId, userId, 'document_uploaded', { documentId, checksum: result.sha256 }); return { ok: true, document: safeDocument(row), version: v } })
}

export function listDealDocuments(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const internal = ['owner', 'reviewer', 'ic_member', 'legal', 'finance', 'read_only'].includes(auth.member.role); const docs = collection(db, 'dataRoomDocuments').filter(row => row.dealId === dealId && (row.visibility !== 'investor_internal' || internal)).map(safeDocument); return { ok: true, documents: docs } }
export function downloadDealDocument(userId, dealId, documentId) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const document = collection(db, 'dataRoomDocuments').find(row => row.id === documentId && row.dealId === dealId && row.status === 'available' && !row.revokedAt && (!row.expiresAt || new Date(row.expiresAt).getTime() > Date.now())); const version = document && collection(db, 'dataRoomDocumentVersions').filter(row => row.documentId === documentId && row.status === 'available').sort((a, b) => b.version - a.version)[0]; if (!document || !version || document.allowDownload === false || (document.visibility === 'investor_internal' && !['owner', 'reviewer', 'ic_member', 'legal', 'finance', 'read_only'].includes(auth.member.role))) return { ok: false, error: 'document_not_found' }; document.lastAccessedAt = now(); audit(db, dealId, userId, 'document_downloaded', { documentId, version: version.version, watermarkRequired: document.watermarkRequired }); const url = version.objectKey ? privateDownloadUrl(version.objectKey, 300) : version.sourceUrl; return { ok: true, document: safeDocument(document), version: { ...version, objectKey: undefined, sourceUrl: undefined }, downloadUrl: url } }) }
export function revokeDealDocument(userId, dealId, documentId) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, allowedRoles: ['owner', 'legal'] }); if (!auth.ok) return auth; const doc = collection(db, 'dataRoomDocuments').find(row => row.id === documentId && row.dealId === dealId); if (!doc) return { ok: false, error: 'document_not_found' }; doc.revokedAt = now(); doc.status = 'revoked'; audit(db, dealId, userId, 'document_revoked', { documentId }); return { ok: true, document: safeDocument(doc) } }) }

function defaultQuestions() { return [{ key: 'problem', prompt: 'What problem does the company solve?', required: true }, { key: 'customers', prompt: 'Who are the target customers?', required: true }, { key: 'traction', prompt: 'What evidence supports traction?', required: true }, { key: 'risks', prompt: 'What are the current material risks?', required: true }, { key: 'fundraise', prompt: 'What is the intended use of funds?', required: true }] }
export function saveQuestionnaireTemplate(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, allowedRoles: ['owner', 'reviewer'] }); if (!auth.ok) return auth; const questions = Array.isArray(body.questions) ? body.questions.filter(row => text(row?.key) && text(row?.prompt)).slice(0, 50).map(row => ({ key: text(row.key), prompt: text(row.prompt), required: row.required === true })) : []; if (!questions.length) return { ok: false, error: 'questionnaire_questions_required' }; for (const row of collection(db, 'investorQuestionnaireTemplates')) if (row.dealId === dealId) row.active = false; const template = { id: createId('iq_template'), dealId, name: text(body.name) || 'Investor Questionnaire', version: collection(db, 'investorQuestionnaireTemplates').filter(row => row.dealId === dealId).length + 1, questions, active: true, createdBy: userId, createdAt: now() }; collection(db, 'investorQuestionnaireTemplates').push(template); audit(db, dealId, userId, 'questionnaire_template_created', { templateId: template.id, version: template.version }); return { ok: true, template } }) }
export function getQuestionnaire(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const template = collection(db, 'investorQuestionnaireTemplates').find(row => row.dealId === dealId && row.active !== false) || { id: 'default', dealId, version: 1, questions: defaultQuestions() }; const submission = collection(db, 'investorQuestionnaireSubmissions').filter(row => row.dealId === dealId).sort((a, b) => b.version - a.version)[0] || null; const project = collection(db, 'projects').find(row => row.id === auth.deal.projectId) || {}; const prefill = { company: project.title || project.name || null, sector: project.sector || project.industry || null, stage: project.stage || null }; const sourceLabels = Object.fromEntries(Object.entries(prefill).filter(([, value]) => value != null).map(([key]) => [key, 'platform_verified'])); return { ok: true, template, prefill, sourceLabels, submission: ['owner', 'reviewer', 'ic_member', 'legal', 'finance'].includes(auth.member.role) || submission?.submittedBy === userId ? submission : submission ? { ...submission, answers: undefined } : null } }
export function saveQuestionnaire(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const answers = body.answers && typeof body.answers === 'object' ? body.answers : {}; const template = collection(db, 'investorQuestionnaireTemplates').find(row => row.dealId === dealId && row.active !== false) || { id: createId('iq_template'), dealId, version: 1, questions: defaultQuestions(), active: true, createdAt: now() }; if (!collection(db, 'investorQuestionnaireTemplates').some(row => row.id === template.id)) collection(db, 'investorQuestionnaireTemplates').push(template); const required = template.questions.filter(q => q.required).map(q => q.key); if (body.submit === true && required.some(key => !text(answers[key]))) return { ok: false, error: 'required_question_missing', missing: required.filter(key => !text(answers[key])) }; const sourceLabels = Object.fromEntries(Object.keys(answers).map(key => [key, body.sourceLabels?.[key] || 'founder_reported'])); const existing = collection(db, 'investorQuestionnaireSubmissions').find(row => row.dealId === dealId && row.submittedBy === userId && row.status !== 'submitted'); const submission = existing || { id: createId('iq_submission'), dealId, submittedBy: userId, version: 1, createdAt: now() }; Object.assign(submission, { answers, sourceLabels, status: body.submit === true ? 'submitted' : 'draft', expiresAt: body.expiresAt || submission.expiresAt || null, submittedAt: body.submit === true ? now() : null, updatedAt: now() }); if (!existing) collection(db, 'investorQuestionnaireSubmissions').push(submission); audit(db, dealId, userId, body.submit === true ? 'questionnaire_completed' : 'questionnaire_saved', { submissionId: submission.id }); notification(db, auth.deal.investorId === userId ? auth.deal.founderId : auth.deal.investorId, body.submit === true ? 'questionnaire_completed' : 'questionnaire_updated', dealId, { submissionId: submission.id }); return { ok: true, submission } }) }

export function technicalDueDiligence(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const analyses = collection(db, 'projectAnalyses').filter(row => row.projectId === auth.deal.projectId && /codebaseanalysisengine|codebase_analysis|codebase/i.test(`${row.engine || ''} ${row.type || ''} ${row.source || ''}`)).sort((a, b) => new Date(b.updatedAt || b.createdAt || 0) - new Date(a.updatedAt || a.createdAt || 0)); const source = analyses[0]; if (!source) return { ok: true, status: 'unavailable', freshness: 'unavailable', reason: 'No CodebaseAnalysisEngine output is available.' }; const ageDays = Math.floor((Date.now() - new Date(source.updatedAt || source.createdAt).getTime()) / 86400000); const blueprint = source.blueprint || source.analysis || {}; const report = { status: 'available', source: 'CodebaseAnalysisEngine', analysisId: source.id, generatedAt: source.updatedAt || source.createdAt, freshness: ageDays > 30 ? 'stale' : 'fresh', sections: { executiveSummary: blueprint.summary || blueprint.executiveSummary || null, architecture: blueprint.architecture || null, developmentHealth: blueprint.developmentHealth || blueprint.health || null, qualityReliability: blueprint.quality || blueprint.reliability || null, securityPosture: blueprint.security || null, technicalDebt: blueprint.technicalDebt || null, investorConsiderations: blueprint.investorConsiderations || null } }; if (report.freshness === 'stale') report.warning = 'Analysis is older than 30 days; request a fresh platform analysis.'; return { ok: true, report } }

export function recordRevenueVerification(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; if (auth.deal.founderId !== userId) return { ok: false, error: 'founder_permission_required' }; const provider = ['stripe', 'paystack', 'flutterwave'].includes(String(body.provider).toLowerCase()) ? String(body.provider).toLowerCase() : null; if (!provider) return { ok: false, error: 'unsupported_revenue_provider' }; const aggregate = { monthlyRevenue: body.monthlyRevenue == null ? null : Number(body.monthlyRevenue), annualRevenue: body.annualRevenue == null ? null : Number(body.annualRevenue), currency: text(body.currency) || null, periodStart: body.periodStart || null, periodEnd: body.periodEnd || null }; if (Object.values(aggregate).some(value => typeof value === 'number' && (!Number.isFinite(value) || value < 0))) return { ok: false, error: 'invalid_revenue_aggregate' }; const row = { id: createId('revenue_verification'), dealId, provider, status: 'founder_reported', aggregate, confidence: 'founder_reported', verifiedAt: null, metadata: { source: 'founder_reported' }, createdBy: userId, updatedAt: now() }; collection(db, 'revenueVerifications').push(row); audit(db, dealId, userId, 'revenue_reported', { verificationId: row.id, provider }); return { ok: true, verification: row } }) }
export function getRevenueVerification(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const row = collection(db, 'revenueVerifications').filter(item => item.dealId === dealId).sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt))[0] || null; return { ok: true, verification: row || { status: 'unverified', aggregate: null } } }

async function providerRevenue(provider, body = {}) {
  const end = body.periodEnd ? new Date(body.periodEnd) : new Date(); const start = body.periodStart ? new Date(body.periodStart) : new Date(end.getTime() - 30 * 86400000)
  if (!Number.isFinite(start.getTime()) || !Number.isFinite(end.getTime()) || start >= end) return { ok: false, error: 'invalid_revenue_period' }
  let url; let headers; let normalize
  if (provider === 'stripe') {
    const key = process.env.REVENUE_STRIPE_READ_ONLY_KEY; if (!key) return { ok: false, error: 'revenue_provider_not_configured' }
    url = `https://api.stripe.com/v1/charges?limit=100&created[gte]=${Math.floor(start.getTime() / 1000)}&created[lte]=${Math.floor(end.getTime() / 1000)}`
    headers = { Authorization: `Bearer ${key}`, ...(body.accountId ? { 'Stripe-Account': text(body.accountId) } : {}) }
    normalize = payload => (payload.data || []).filter(row => row.paid && !row.refunded).map(row => ({ amount: Number(row.amount || 0) / 100, currency: String(row.currency || '').toUpperCase() }))
  } else if (provider === 'paystack') {
    const key = process.env.REVENUE_PAYSTACK_READ_ONLY_KEY; if (!key) return { ok: false, error: 'revenue_provider_not_configured' }
    url = `https://api.paystack.co/transaction?perPage=100&from=${encodeURIComponent(start.toISOString())}&to=${encodeURIComponent(end.toISOString())}`; headers = { Authorization: `Bearer ${key}` }
    normalize = payload => (payload.data || []).filter(row => row.status === 'success').map(row => ({ amount: Number(row.amount || 0) / 100, currency: String(row.currency || '').toUpperCase() }))
  } else if (provider === 'flutterwave') {
    const key = process.env.REVENUE_FLUTTERWAVE_READ_ONLY_KEY; if (!key) return { ok: false, error: 'revenue_provider_not_configured' }
    url = `https://api.flutterwave.com/v3/transactions?from=${start.toISOString().slice(0, 10)}&to=${end.toISOString().slice(0, 10)}&status=successful`; headers = { Authorization: `Bearer ${key}` }
    normalize = payload => (payload.data || []).filter(row => row.status === 'successful').map(row => ({ amount: Number(row.amount || 0), currency: String(row.currency || '').toUpperCase() }))
  } else return { ok: false, error: 'unsupported_revenue_provider' }
  try { const response = await fetch(url, { headers, signal: AbortSignal.timeout(15000) }); if (!response.ok) return { ok: false, error: 'revenue_provider_unavailable' }; const transactions = normalize(await response.json()); const currencies = [...new Set(transactions.map(row => row.currency).filter(Boolean))]; if (currencies.length > 1) return { ok: false, error: 'mixed_currency_requires_separate_verification' }; return { ok: true, aggregate: { grossRevenue: transactions.reduce((sum, row) => sum + row.amount, 0), transactionCount: transactions.length, currency: currencies[0] || null, periodStart: start.toISOString(), periodEnd: end.toISOString() } } } catch { return { ok: false, error: 'revenue_provider_unavailable' } }
}
export async function refreshRevenueVerification(userId, dealId, body = {}) {
  const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; if (auth.deal.founderId !== userId) return { ok: false, error: 'founder_permission_required' }
  const provider = String(body.provider || '').toLowerCase(); const result = await providerRevenue(provider, body); if (!result.ok) return result
  return updateDb(state => { const row = { id: createId('revenue_verification'), dealId, provider, status: 'verified', aggregate: result.aggregate, confidence: 'processor_verified', verifiedAt: now(), metadata: { source: 'read_only_processor_aggregate' }, createdBy: userId, updatedAt: now() }; collection(state, 'revenueVerifications').push(row); audit(state, dealId, userId, 'revenue_verified', { verificationId: row.id, provider, transactionCount: result.aggregate.transactionCount }); notification(state, auth.deal.investorId, 'revenue_verification_refreshed', dealId, { verificationId: row.id }); return { ok: true, verification: row } })
}

export function createReferenceRequest(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, investorOnly: true }); if (!auth.ok) return auth; const token = randomBytes(24).toString('hex'); const request = { id: createId('reference'), dealId, tokenHash: hashToken(token), nomineeRole: text(body.nomineeRole) || 'reference', status: 'requested', expiresAt: body.expiresAt || new Date(Date.now() + 14 * 86400000).toISOString(), questions: Array.isArray(body.questions) && body.questions.length ? body.questions.slice(0, 12) : ['How did you work with the founder?', 'What are the founder’s strongest execution traits?', 'What should an investor monitor?'], createdAt: now(), updatedAt: now() }; collection(db, 'referenceRequests').push(request); audit(db, dealId, userId, 'reference_requested', { requestId: request.id }); return { ok: true, request: { ...request, token } } }) }
export function submitReference(token, body = {}) { return updateDb(db => { const request = collection(db, 'referenceRequests').find(row => row.tokenHash === hashToken(token) && row.status === 'requested' && new Date(row.expiresAt).getTime() > Date.now()); if (!request) return { ok: false, error: 'reference_token_invalid' }; const answers = body.answers && typeof body.answers === 'object' ? body.answers : {}; request.status = 'submitted'; request.response = { themes: Object.values(answers).filter(value => typeof value === 'string').map(value => value.slice(0, 500)), submittedAt: now() }; request.tokenHash = null; request.updatedAt = now(); audit(db, request.dealId, null, 'reference_check_completed', { requestId: request.id }); return { ok: true, response: { requestId: request.id, status: request.status, themes: request.response.themes } } }) }
export function listReferences(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true, investorOnly: true }); if (!auth.ok) return auth; return { ok: true, references: collection(db, 'referenceRequests').filter(row => row.dealId === dealId).map(row => ({ id: row.id, nomineeRole: row.nomineeRole, status: row.status, expiresAt: row.expiresAt, response: row.response ? { themes: row.response.themes, submittedAt: row.response.submittedAt } : null })) } }

export function addDealParticipant(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, allowedRoles: ['owner'] }); if (!auth.ok) return auth; const target = text(body.userId); const role = text(body.role); if (!target || !roles.has(role) || role === 'owner') return { ok: false, error: 'invalid_participant' }; if (collection(db, 'dealRoomParticipants').some(row => row.dealId === dealId && row.userId === target && row.status !== 'revoked')) return { ok: false, error: 'participant_exists' }; const participant = { id: createId('deal_participant'), dealId, userId: target, role, status: 'active', addedBy: userId, createdAt: now() }; collection(db, 'dealRoomParticipants').push(participant); audit(db, dealId, userId, 'deal_participant_added', { participantId: participant.id, role }); return { ok: true, participant } }) }
export function listDealParticipants(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; return { ok: true, participants: collection(db, 'dealRoomParticipants').filter(row => row.dealId === dealId && row.status !== 'revoked').map(({ userId: memberId, ...row }) => ({ ...row, userId: memberId })) } }
export function revokeDealParticipant(userId, dealId, participantId) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, allowedRoles: ['owner'] }); if (!auth.ok) return auth; const participant = collection(db, 'dealRoomParticipants').find(row => row.id === participantId && row.dealId === dealId && row.role !== 'owner' && row.status !== 'revoked'); if (!participant) return { ok: false, error: 'participant_not_found' }; participant.status = 'revoked'; participant.revokedAt = now(); participant.revokedBy = userId; audit(db, dealId, userId, 'deal_participant_revoked', { participantId }); return { ok: true, participant } }) }
export function updateIcReview(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, allowedRoles: ['owner', 'ic_member'] }); if (!auth.ok) return auth; const row = collection(db, 'icReviews').find(item => item.dealId === dealId && item.investorId === userId) || { id: createId('ic_review'), dealId, investorId: userId, createdAt: now() }; if (!collection(db, 'icReviews').some(item => item.id === row.id)) collection(db, 'icReviews').push(row); for (const key of ['thesis', 'risks', 'mitigants', 'strengths', 'openQuestions', 'proposedCheck', 'proposedValuation', 'conditions', 'recommendation']) if (body[key] !== undefined) row[key] = text(body[key]); row.recommendation = ['proceed', 'hold', 'pass'].includes(row.recommendation) ? row.recommendation : 'hold'; row.updatedAt = now(); collection(db, 'icApprovalHistory').push({ id: createId('ic_approval'), reviewId: row.id, actorId: userId, recommendation: row.recommendation, comment: text(body.comment) || null, createdAt: now() }); audit(db, dealId, userId, 'ic_decision_recorded', { reviewId: row.id, recommendation: row.recommendation }); return { ok: true, review: row } }) }
export function termSheetAction(userId, dealId, action, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; if (['share', 'finalize'].includes(action) && !['owner', 'legal'].includes(auth.member.role)) return { ok: false, error: 'investor_permission_required' }; if (action === 'comment' && !['diligence_owner', 'owner', 'legal'].includes(auth.member.role)) return { ok: false, error: 'term_sheet_comment_permission_required' }; const versions = collection(db, 'termSheetVersions'); const row = versions.filter(item => item.dealId === dealId).sort((a, b) => b.version - a.version)[0]; if (action === 'create') return { ok: false, error: 'use_existing_term_sheet_create' }; if (!row) return { ok: false, error: 'term_sheet_not_found' }; const allowed = { share: ['draft'], comment: ['shared_with_founder'], finalize: ['commented', 'shared_with_founder'] }; if (!allowed[action]?.includes(row.status)) return { ok: false, error: 'invalid_term_sheet_transition' }; row.status = action === 'share' ? 'shared_with_founder' : action === 'comment' ? 'commented' : 'final'; row.comments = action === 'comment' ? [...(row.comments || []), { authorId: userId, content: text(body.comment) || '', createdAt: now() }] : row.comments; row.updatedAt = now(); const auditAction = action === 'share' ? 'term_sheet_shared' : action === 'comment' ? 'term_sheet_commented' : 'term_sheet_finalized'; audit(db, dealId, userId, auditAction, { version: row.version }); notification(db, action === 'comment' ? auth.deal.investorId : auth.deal.founderId, auditAction, dealId, { version: row.version }); return { ok: true, termSheet: row } }) }
export function listTermSheets(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; return { ok: true, termSheets: collection(db, 'termSheetVersions').filter(row => row.dealId === dealId).sort((a, b) => b.version - a.version) } }
export function upsertClosingItem(userId, dealId, body = {}) { return updateDb(db => { const auth = authorize(db, userId, dealId, { nda: true, allowedRoles: ['owner', 'legal', 'finance'] }); if (!auth.ok) return auth; const status = ['outstanding', 'in_progress', 'complete', 'waived'].includes(body.status) ? body.status : 'outstanding'; const row = body.id ? collection(db, 'dealClosingItems').find(item => item.id === body.id && item.dealId === dealId) : null; if (body.id && !row) return { ok: false, error: 'closing_item_not_found' }; const item = row || { id: createId('closing_item'), dealId, createdBy: userId, createdAt: now() }; Object.assign(item, { label: text(body.label) || item.label, required: body.required !== false, status, ownerId: body.ownerId || null, dueDate: body.dueDate || null, evidenceDocumentId: body.evidenceDocumentId || null, updatedAt: now() }); if (!item.label) return { ok: false, error: 'closing_item_label_required' }; if (!row) collection(db, 'dealClosingItems').push(item); audit(db, dealId, userId, 'closing_item_updated', { closingItemId: item.id, status: item.status }); return { ok: true, item } }) }
export function closingReadiness(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const items = collection(db, 'diligenceItems').filter(row => row.dealId === dealId && row.required !== false); const requests = collection(db, 'diligenceEvidenceLinks').filter(row => row.dealId === dealId && row.required !== false); const custom = collection(db, 'dealClosingItems').filter(row => row.dealId === dealId); const conditions = [{ key: 'nda', label: 'NDA signed', complete: ndaFor(db, auth.deal, auth.deal.investorId) }, { key: 'diligence', label: 'Required diligence accepted', complete: items.length > 0 && items.every(row => ['accepted', 'waived'].includes(row.status)) }, { key: 'evidence', label: 'Required evidence requests complete', complete: requests.every(row => ['accepted', 'completed', 'waived'].includes(row.status)) }, { key: 'term_sheet', label: 'Final term sheet', complete: collection(db, 'termSheetVersions').some(row => row.dealId === dealId && row.status === 'final') }, ...custom.map(row => ({ key: row.id, label: row.label, complete: !row.required || ['complete', 'waived'].includes(row.status), status: row.status }))]; return { ok: true, ready: conditions.every(row => row.complete), conditions } }
export function investorPack(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const readiness = closingReadiness(userId, dealId); const tech = technicalDueDiligence(userId, dealId); const docs = collection(db, 'dataRoomDocuments').filter(row => row.dealId === dealId).map(safeDocument); const items = collection(db, 'diligenceItems').filter(row => row.dealId === dealId); const pack = { id: createId('investor_pack'), dealId, generatedAt: now(), cover: { dealStatus: auth.deal.state, ndaStatus: ndaFor(db, auth.deal, auth.deal.investorId) ? 'signed' : 'required', diligenceCompletion: items.length ? Math.round(items.filter(row => ['accepted', 'waived'].includes(row.status)).length / items.length * 100) : 0, dataFreshness: tech.report?.freshness || 'unavailable' }, sections: { checklist: items, documents: docs, technicalDueDiligence: tech.report || null, closingReadiness: readiness.conditions }, disclaimer: 'Information is labelled by source and is not investment or legal advice.' }; collection(db, 'investorPacks').push(pack); audit(db, dealId, userId, 'investor_pack_generated', { packId: pack.id }); return { ok: true, pack } }
export function verifyDealAudit(userId, dealId) { const db = readDb(); const auth = authorize(db, userId, dealId, { nda: true }); if (!auth.ok) return auth; const events = collection(db, 'dealAuditEvents').filter(row => row.dealId === dealId); let previous = 'GENESIS'; const failures = []; for (const event of events) { const expected = sha(`${previous}|${event.dealId}|${event.actorId || ''}|${event.action}|${event.sourceDataHash}|${event.createdAt}`); if (event.prevHash !== previous || event.eventHash !== expected) failures.push(event.id); previous = event.eventHash }; return { ok: true, valid: failures.length === 0, eventCount: events.length, failures } }
export function listComparables(userId, filters = {}) { const db = readDb(); const rows = collection(db, 'comparableTransactions').filter(row => row.active !== false && (!filters.region || row.region === filters.region) && (!filters.sector || row.sector === filters.sector)); return { ok: true, comparables: rows.map(({ sourceUrl, ...row }) => ({ ...row, sourceAttributed: Boolean(row.source), hasSourceUrl: Boolean(sourceUrl) })), disclaimer: 'Reference ranges are not valuations or investment advice.' } }
export function upsertComparable(adminId, body = {}) { return updateDb(db => { const required = ['company', 'sector', 'region', 'transactionType', 'source']; if (required.some(key => !text(body[key]))) return { ok: false, error: 'comparable_fields_required' }; const amount = body.amount == null ? null : Number(body.amount); if (amount != null && (!Number.isFinite(amount) || amount < 0)) return { ok: false, error: 'invalid_comparable_amount' }; const row = body.id ? collection(db, 'comparableTransactions').find(item => item.id === body.id) : null; const next = row || { id: createId('comparable'), createdAt: now() }; Object.assign(next, { company: text(body.company), sector: text(body.sector), region: text(body.region), transactionType: text(body.transactionType), amount, currency: text(body.currency) || null, announcedAt: body.announcedAt || null, source: text(body.source), sourceUrl: /^https?:\/\//i.test(body.sourceUrl || '') ? body.sourceUrl : null, active: body.active !== false, updatedBy: adminId, updatedAt: now() }); if (!row) collection(db, 'comparableTransactions').push(next); return { ok: true, comparable: next } }) }
export function runDealRoomMaintenance() { return updateDb(db => { const created = []; const current = Date.now(); for (const row of collection(db, 'diligenceItems').concat(collection(db, 'diligenceEvidenceLinks'))) { if (row.dueDate && new Date(row.dueDate).getTime() < current && !['accepted', 'waived', 'completed', 'overdue'].includes(row.status)) { row.status = 'overdue'; row.updatedAt = now(); created.push(row.id); const deal = dealFor(db, row.dealId); notification(db, row.ownerId || deal?.founderId, 'deal_room_deadline_overdue', row.dealId, { itemId: row.id }) } } for (const request of collection(db, 'referenceRequests')) { const expiry = new Date(request.expiresAt).getTime(); if (request.status === 'requested' && expiry <= current) { request.status = 'expired'; request.updatedAt = now() } else if (request.status === 'requested' && expiry - current < 48 * 60 * 60 * 1000 && !request.reminderSentAt) { request.reminderSentAt = now(); const deal = dealFor(db, request.dealId); notification(db, deal?.investorId, 'reference_expiry_warning', request.dealId, { requestId: request.id }) } } for (const row of collection(db, 'investorQuestionnaireSubmissions')) if (row.status === 'draft' && row.expiresAt && new Date(row.expiresAt).getTime() <= current) { row.status = 'expired'; row.updatedAt = now() } for (const row of collection(db, 'dataRoomDocuments')) if (row.status === 'available' && row.expiresAt && new Date(row.expiresAt).getTime() <= current) { row.status = 'expired'; row.updatedAt = now() } return { ok: true, overdueCount: created.length } }) }

export { audit }
