import fs from 'node:fs/promises'
import pg from 'pg'
import { readDb } from '../config/database.js'

let pool = null; let timer = null
const url = () => process.env.TRUST_DATABASE_URL || process.env.DATABASE_URL
const json = value => JSON.stringify(value || {})
const timestamp = value => value || new Date().toISOString()

export async function syncTrustProjection() {
  if (!pool) return { enabled: false }
  const db = readDb(); const client = await pool.connect()
  try {
    await client.query('BEGIN')
    for (const row of db.userRoles || []) await client.query(`INSERT INTO trust_user_roles(id,user_id,role,status,assurance,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,role) DO UPDATE SET status=EXCLUDED.status,assurance=EXCLUDED.assurance,updated_at=EXCLUDED.updated_at`, [row.id, row.userId, row.role, row.status || 'active', row.assurance || 'CLAIMED', timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.verificationProfiles || []) await client.query(`INSERT INTO trust_verification_profiles(id,user_id,role,assurance,status,trust_score,evidence_quality,verified_by,verified_at,expires_at,last_reviewed_at,payload,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(user_id,role) DO UPDATE SET assurance=EXCLUDED.assurance,status=EXCLUDED.status,trust_score=EXCLUDED.trust_score,evidence_quality=EXCLUDED.evidence_quality,verified_by=EXCLUDED.verified_by,verified_at=EXCLUDED.verified_at,expires_at=EXCLUDED.expires_at,last_reviewed_at=EXCLUDED.last_reviewed_at,payload=EXCLUDED.payload,updated_at=EXCLUDED.updated_at`, [row.id, row.userId, row.role, row.assurance || 'CLAIMED', row.status || 'claimed', Number(row.trustScore || 0), row.evidenceQuality || null, row.verifiedBy || null, row.verifiedAt || null, row.expiresAt || null, row.lastReviewedAt || null, json(row), timestamp(row.updatedAt)])
    for (const row of db.verificationRequests || []) await client.query(`INSERT INTO trust_verification_requests(id,user_id,role,claim_type,requested_capability,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`, [row.id, row.userId, row.role, row.claimType || 'role', row.requestedCapability || null, row.status, timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.verificationEvidence || []) await client.query(`INSERT INTO trust_verification_evidence(id,request_id,user_id,role,method,strength,status,source,object_key,content_type,size_bytes,malware_status,metadata,ai_advisory,submitted_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET strength=EXCLUDED.strength,status=EXCLUDED.status,metadata=EXCLUDED.metadata,ai_advisory=EXCLUDED.ai_advisory`, [row.id, row.requestId, row.userId, row.role, row.method, row.strength, row.status, row.source || null, row.objectKey || row.metadata?.objectKey || null, row.contentType || null, Number(row.sizeBytes || 0) || null, row.malwareStatus || null, json(row.metadata), row.aiAdvisory ? json(row.aiAdvisory) : null, timestamp(row.submittedAt)])
    for (const row of db.organizations || []) await client.query(`INSERT INTO trust_organizations(id,name,website,country,type,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,website=EXCLUDED.website,country=EXCLUDED.country,type=EXCLUDED.type,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`, [row.id, row.name, row.website || null, row.country || null, row.type || 'other', row.status || 'claimed', row.createdBy, timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.organizationDomains || []) await client.query(`INSERT INTO trust_organization_domains(id,organization_id,domain,status,verified_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(domain) DO UPDATE SET organization_id=EXCLUDED.organization_id,status=EXCLUDED.status,verified_at=EXCLUDED.verified_at,updated_at=EXCLUDED.updated_at`, [row.id, row.organizationId, row.domain, row.status, row.verifiedAt || null, timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.organizationMemberships || []) await client.query(`INSERT INTO trust_organization_memberships(id,organization_id,user_id,role,status,verified,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id,user_id) DO UPDATE SET role=EXCLUDED.role,status=EXCLUDED.status,verified=EXCLUDED.verified,updated_at=EXCLUDED.updated_at`, [row.id, row.organizationId, row.userId, row.role, row.status, Boolean(row.verified), timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.riskProfiles || []) await client.query(`INSERT INTO trust_risk_profiles(id,user_id,state,note,updated_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id) DO UPDATE SET state=EXCLUDED.state,note=EXCLUDED.note,updated_by=EXCLUDED.updated_by,updated_at=EXCLUDED.updated_at`, [row.id, row.userId, row.state, row.note || null, row.updatedBy || null, timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.capabilityPolicies || []) await client.query(`INSERT INTO trust_capability_policies(capability,policy,active,updated_by,updated_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(capability) DO UPDATE SET policy=EXCLUDED.policy,active=EXCLUDED.active,updated_by=EXCLUDED.updated_by,updated_at=EXCLUDED.updated_at`, [row.capability, json(row.policy), row.active !== false, row.updatedBy || null, timestamp(row.updatedAt)])
    for (const row of db.authorizationAuditLogs || []) await client.query(`INSERT INTO trust_authorization_audit(id,user_id,capability,allowed,code,active_role,assurance,risk_state,policy_version,context,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO NOTHING`, [row.id, row.userId, row.capability, Boolean(row.allowed), row.code, row.activeRole || null, row.assurance || null, row.riskState || null, row.policyVersion || 'capability-v1', json(row.context), timestamp(row.createdAt)])
    for (const row of db.capabilityConsumptions || []) await client.query(`INSERT INTO trust_capability_consumptions(id,idempotency_key,user_id,capability,funding_source,credits,status,response_status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(idempotency_key) DO UPDATE SET status=EXCLUDED.status,response_status=EXCLUDED.response_status,updated_at=EXCLUDED.updated_at`, [row.id, row.idempotencyKey, row.userId, row.capability, row.fundingSource, Number(row.credits || 0), row.status, row.responseStatus || null, timestamp(row.createdAt), timestamp(row.updatedAt)])
    for (const row of db.capabilityAnalytics || []) await client.query(`INSERT INTO trust_capability_analytics(id,user_id,capability,event_type,role,assurance,code,metadata,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING`, [row.id, row.userId || null, row.capability, row.eventType, row.role || null, row.assurance || null, row.code || null, json(row.metadata), timestamp(row.createdAt)])
    await client.query('COMMIT'); return { enabled: true }
  } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() }
}

export async function initializeTrustPostgresProjection() {
  if (!url()) return { enabled: false }
  pool = new pg.Pool({ connectionString: url(), max: Math.max(1, Number(process.env.TRUST_DB_POOL_SIZE || 5)), ssl: /sslmode=require/.test(url()) ? { rejectUnauthorized: process.env.TRUST_DB_SSL_REJECT_UNAUTHORIZED !== 'false' } : undefined })
  const sql = await fs.readFile(new URL('../../migrations/postgres/002_trust_capability_authorization.sql', import.meta.url), 'utf8'); await pool.query(sql); await syncTrustProjection()
  timer = setInterval(() => { syncTrustProjection().catch(error => console.error(JSON.stringify({ event: 'trust_projection_failed', error: error.message }))) }, Math.max(5000, Number(process.env.TRUST_PROJECTION_INTERVAL_MS || 30000))); timer.unref?.()
  return { enabled: true }
}
