import pg from 'pg'

let pool = null
const url = () => process.env.FINANCE_DATABASE_URL || process.env.DATABASE_URL
const readEnabled = () => process.env.FINANCE_READ_SOURCE === 'postgres'
const fallback = () => process.env.FINANCE_READ_FALLBACK_SQLITE !== 'false'
function getPool() { if (!url()) throw new Error('FINANCE_DATABASE_URL or DATABASE_URL is required'); pool ||= new pg.Pool({ connectionString: url(), max: Math.max(1, Number(process.env.FINANCE_READ_POOL_SIZE || process.env.FINANCE_DB_POOL_SIZE || 5)), connectionTimeoutMillis: Number(process.env.FINANCE_DB_CONNECTION_TIMEOUT_MS || 5000), ssl: /sslmode=require/.test(url()) ? { rejectUnauthorized: process.env.FINANCE_DB_SSL_REJECT_UNAUTHORIZED !== 'false' } : undefined }); return pool }
const map = row => ({ ...(row.payload || {}), id: row.id, userId: row.user_id, creditBalance: row.balance == null ? undefined : Number(row.balance), balance: row.balance == null ? undefined : Number(row.balance), currency: row.currency, deltaCredits: row.delta_credits == null ? undefined : Number(row.delta_credits), reservedCredits: row.reserved_credits == null ? undefined : Number(row.reserved_credits), status: row.status, amount: row.amount == null ? undefined : Number(row.amount), credits: row.credits == null ? undefined : Number(row.credits), createdAt: row.created_at, updatedAt: row.updated_at })
export async function walletAccount(userId) { const result = await getPool().query('SELECT * FROM core_wallet_accounts WHERE user_id=$1', [userId]); return result.rows[0] ? map(result.rows[0]) : null }
export async function walletCollection(userId, name) { const tables = { creditLedger: 'core_credit_ledger', usageReservations: 'core_usage_reservations', paymentIntents: 'core_payment_intents', subscriptions: 'core_subscriptions' }; const table = tables[name]; if (!table) throw new Error('unsupported finance collection'); const result = await getPool().query(`SELECT * FROM ${table} WHERE user_id=$1 ORDER BY created_at DESC`, [userId]); return result.rows.map(map) }
export async function walletSummary(userId) { const [account, ledger, reservations, payments] = await Promise.all([walletAccount(userId), walletCollection(userId, 'creditLedger'), walletCollection(userId, 'usageReservations'), walletCollection(userId, 'paymentIntents')]); const creditBalance = Number(account?.creditBalance || 0) + ledger.reduce((sum, row) => sum + Number(row.deltaCredits || row.credits || 0), 0); return { account: account || { userId, creditBalance, currency: 'USD' }, creditBalance, lifetimeCreditsUsed: Math.abs(ledger.filter(row => row.type === 'usage_settlement').reduce((sum, row) => sum + Number(row.deltaCredits || 0), 0)), pendingPayments: payments.filter(row => row.status === 'pending').length, pendingReservations: reservations.filter(row => row.status === 'reserved').length } }
export function financeReadEnabled() { return readEnabled() }
export function financeReadFallbackEnabled() { return fallback() }
export async function closeFinanceRepository() { if (pool) await pool.end(); pool = null }
