import pg from 'pg'
import { readDb } from '../config/database.js'

let pool = null
const url = () => process.env.ORGANIZATION_DATABASE_URL || process.env.DATABASE_URL
const readEnabled = () => process.env.ORGANIZATION_READ_SOURCE === 'postgres'
const writeEnabled = () => process.env.ORGANIZATION_WRITE_SOURCE === 'postgres'
const fallback = kind => process.env[`ORGANIZATION_${kind}_FALLBACK_SQLITE`] !== 'false'
function getPool() { if (!url()) throw new Error('ORGANIZATION_DATABASE_URL or DATABASE_URL is required'); pool ||= new pg.Pool({ connectionString: url(), max: Math.max(1, Number(process.env.ORGANIZATION_DB_POOL_SIZE || 5)), connectionTimeoutMillis: Number(process.env.ORGANIZATION_DB_CONNECTION_TIMEOUT_MS || 5000), ssl: /sslmode=require/.test(url()) ? { rejectUnauthorized: process.env.ORGANIZATION_DB_SSL_REJECT_UNAUTHORIZED !== 'false' } : undefined }); return pool }
const j = value => JSON.stringify(value || {})
export async function listActions(organizationId, filters = {}) { const clauses = ['organization_id=$1']; const values = [organizationId]; for (const key of ['status','priority','owner_id','source_type']) if (filters[key] !== undefined) { values.push(filters[key]); clauses.push(`${key}=$${values.length}`) } const result = await getPool().query(`SELECT * FROM organization_actions WHERE ${clauses.join(' AND ')} ORDER BY due_date NULLS LAST,created_at DESC`, values); return result.rows.map(row => ({ id: row.id, organizationId: row.organization_id, title: row.title, reason: row.reason, evidence: row.evidence, sourceType: row.source_type, sourceId: row.source_id, ownerId: row.owner_id, priority: row.priority, dueDate: row.due_date, status: row.status, createdBy: row.created_by, createdAt: row.created_at, updatedAt: row.updated_at })) }
export async function listKpis(organizationId) { const definitions = await getPool().query('SELECT * FROM organization_kpi_definitions WHERE organization_id=$1 ORDER BY created_at', [organizationId]); const values = await getPool().query('SELECT * FROM organization_kpi_values WHERE organization_id=$1 ORDER BY period_end DESC NULLS LAST,created_at DESC', [organizationId]); return definitions.rows.map(row => ({ id: row.id, organizationId: row.organization_id, name: row.name, definition: row.definition, unit: row.unit, target: row.target == null ? null : Number(row.target), frequency: row.frequency, ownerId: row.owner_id, visibility: row.visibility, createdBy: row.created_by, createdAt: row.created_at, updatedAt: row.updated_at, values: values.rows.filter(value => value.definition_id === row.id).slice(0, 12).map(value => ({ id: value.id, definitionId: value.definition_id, organizationId: value.organization_id, value: Number(value.value), source: value.source, periodStart: value.period_start, periodEnd: value.period_end, recordedBy: value.recorded_by, createdAt: value.created_at })) })) }
export async function listCollection(table, organizationId) { const allowed = new Set(['organization_cohorts','organization_partners','organization_resources','organization_report_schedules']); if (!allowed.has(table)) throw new Error('invalid organization collection'); const result = await getPool().query(`SELECT * FROM ${table} WHERE organization_id=$1 ORDER BY updated_at DESC NULLS LAST,created_at DESC`, [organizationId]); return result.rows.map(row => { const value = { ...row }; for (const key of Object.keys(value)) { const camel = key.replace(/_([a-z])/g, (_, c) => c.toUpperCase()); if (camel !== key) { value[camel] = value[key]; delete value[key] } } return value }) }
export async function syncOrganizationAggregate(organizationId) { if (!writeEnabled()) return { enabled: false }; const db = readDb(); const client = await getPool().connect(); try { await client.query('BEGIN'); for (const row of (db.organizationActions || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_actions(id,organization_id,title,reason,evidence,source_type,source_id,owner_id,priority,due_date,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,reason=EXCLUDED.reason,evidence=EXCLUDED.evidence,owner_id=EXCLUDED.owner_id,priority=EXCLUDED.priority,due_date=EXCLUDED.due_date,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.title,row.reason||null,j(row.evidence),row.sourceType,row.sourceId||null,row.ownerId||null,row.priority,row.dueDate||null,row.status,row.createdBy,row.createdAt,row.updatedAt]); for (const row of (db.organizationKpiDefinitions || []).filter(x => x.organizationId === organizationId)) { await client.query(`INSERT INTO organization_kpi_definitions(id,organization_id,name,definition,unit,target,frequency,owner_id,visibility,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,definition=EXCLUDED.definition,unit=EXCLUDED.unit,target=EXCLUDED.target,frequency=EXCLUDED.frequency,owner_id=EXCLUDED.owner_id,visibility=EXCLUDED.visibility,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.name,row.definition||null,row.unit,row.target,row.frequency,row.ownerId||null,row.visibility,row.createdBy,row.createdAt,row.updatedAt]) } for (const row of (db.organizationKpiValues || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_kpi_values(id,definition_id,organization_id,value,source,period_start,period_end,recorded_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING`, [row.id,row.definitionId,organizationId,row.value,row.source,row.periodStart||null,row.periodEnd||null,row.recordedBy,row.createdAt]); await client.query('COMMIT'); return { enabled: true } } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } }
export function organizationReadEnabled() { return readEnabled() }
export function organizationWriteEnabled() { return writeEnabled() }
export function organizationFallbackEnabled(kind) { return fallback(kind) }
export async function closeOrganizationOperationsRepository() { if (pool) await pool.end(); pool = null }
