import { readDb as readAuthorityDb } from '../config/database.js'
import fs from 'node:fs/promises'
import { getPlatformPool, closePlatformPool } from './platformCollectionRepository.js'

const url = () => process.env.ORGANIZATION_DATABASE_URL || process.env.DATABASE_URL
const readEnabled = () => process.env.ORGANIZATION_READ_SOURCE === 'postgres'
const writeEnabled = () => process.env.ORGANIZATION_WRITE_SOURCE === 'postgres'
const fallback = kind => process.env[`ORGANIZATION_${kind}_FALLBACK_SQLITE`] !== 'false'
function getPool() { if (!url()) throw new Error('ORGANIZATION_DATABASE_URL or DATABASE_URL is required'); return getPlatformPool() }
export async function initializeOrganizationCommercialProjection() { if (!url()) return { enabled: false }; await getPool().query(await fs.readFile(new URL('../../migrations/postgres/006_organization_intelligence_operations.sql', import.meta.url), 'utf8')); await getPool().query(await fs.readFile(new URL('../../migrations/postgres/017_organization_commercialization.sql', import.meta.url), 'utf8')); return { enabled: true } }
const j = value => JSON.stringify(value || {})
export async function listActions(organizationId, filters = {}) { const clauses = ['organization_id=$1']; const values = [organizationId]; for (const key of ['status','priority','owner_id','source_type']) if (filters[key] !== undefined) { values.push(filters[key]); clauses.push(`${key}=$${values.length}`) } const result = await getPool().query(`SELECT * FROM organization_actions WHERE ${clauses.join(' AND ')} ORDER BY due_date NULLS LAST,created_at DESC`, values); return result.rows.map(row => ({ id: row.id, organizationId: row.organization_id, title: row.title, reason: row.reason, evidence: row.evidence, sourceType: row.source_type, sourceId: row.source_id, ownerId: row.owner_id, priority: row.priority, dueDate: row.due_date, status: row.status, createdBy: row.created_by, createdAt: row.created_at, updatedAt: row.updated_at })) }
export async function listKpis(organizationId) { const definitions = await getPool().query('SELECT * FROM organization_kpi_definitions WHERE organization_id=$1 ORDER BY created_at', [organizationId]); const values = await getPool().query('SELECT * FROM organization_kpi_values WHERE organization_id=$1 ORDER BY period_end DESC NULLS LAST,created_at DESC', [organizationId]); return definitions.rows.map(row => ({ id: row.id, organizationId: row.organization_id, name: row.name, definition: row.definition, unit: row.unit, target: row.target == null ? null : Number(row.target), frequency: row.frequency, ownerId: row.owner_id, visibility: row.visibility, createdBy: row.created_by, createdAt: row.created_at, updatedAt: row.updated_at, values: values.rows.filter(value => value.definition_id === row.id).slice(0, 12).map(value => ({ id: value.id, definitionId: value.definition_id, organizationId: value.organization_id, value: Number(value.value), source: value.source, periodStart: value.period_start, periodEnd: value.period_end, recordedBy: value.recorded_by, createdAt: value.created_at })) })) }
export async function listCollection(table, organizationId) { const allowed = new Set(['organization_cohorts','organization_partners','organization_resources','organization_report_schedules']); if (!allowed.has(table)) throw new Error('invalid organization collection'); const result = await getPool().query(`SELECT * FROM ${table} WHERE organization_id=$1 ORDER BY updated_at DESC NULLS LAST,created_at DESC`, [organizationId]); return result.rows.map(row => { const value = { ...row }; for (const key of Object.keys(value)) { const camel = key.replace(/_([a-z])/g, (_, c) => c.toUpperCase()); if (camel !== key) { value[camel] = value[key]; delete value[key] } } return value }) }
export async function syncOrganizationAggregate(organizationId) { if (!writeEnabled()) return { enabled: false }; const db = readAuthorityDb(); const client = await getPool().connect(); try { await client.query('BEGIN'); for (const row of (db.organizationActions || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_actions(id,organization_id,title,reason,evidence,source_type,source_id,owner_id,priority,due_date,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,reason=EXCLUDED.reason,evidence=EXCLUDED.evidence,owner_id=EXCLUDED.owner_id,priority=EXCLUDED.priority,due_date=EXCLUDED.due_date,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.title,row.reason||null,j(row.evidence),row.sourceType,row.sourceId||null,row.ownerId||null,row.priority,row.dueDate||null,row.status,row.createdBy,row.createdAt,row.updatedAt]); for (const row of (db.organizationKpiDefinitions || []).filter(x => x.organizationId === organizationId)) { await client.query(`INSERT INTO organization_kpi_definitions(id,organization_id,name,definition,unit,target,frequency,owner_id,visibility,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,definition=EXCLUDED.definition,unit=EXCLUDED.unit,target=EXCLUDED.target,frequency=EXCLUDED.frequency,owner_id=EXCLUDED.owner_id,visibility=EXCLUDED.visibility,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.name,row.definition||null,row.unit,row.target,row.frequency,row.ownerId||null,row.visibility,row.createdBy,row.createdAt,row.updatedAt]) } for (const row of (db.organizationKpiValues || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_kpi_values(id,definition_id,organization_id,value,source,period_start,period_end,recorded_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING`, [row.id,row.definitionId,organizationId,row.value,row.source,row.periodStart||null,row.periodEnd||null,row.recordedBy,row.createdAt]); await client.query('COMMIT'); return { enabled: true } } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } }
export async function syncOrganizationCollections(organizationId) { if (!writeEnabled()) return { enabled: false }; const db = readAuthorityDb(); const client = await getPool().connect(); try { await client.query('BEGIN'); for (const row of (db.organizationCohorts || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_cohorts(id,organization_id,program_id,name,status,start_date,end_date,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,status=EXCLUDED.status,start_date=EXCLUDED.start_date,end_date=EXCLUDED.end_date,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.programId||null,row.name,row.status||'planned',row.startDate||null,row.endDate||null,row.createdBy,row.createdAt,row.updatedAt]); for (const row of (db.organizationPartners || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_partners(id,organization_id,name,type,status,programs,notes,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,type=EXCLUDED.type,status=EXCLUDED.status,programs=EXCLUDED.programs,notes=EXCLUDED.notes,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.name,row.type,row.status,j(row.programs),row.notes||null,row.createdBy,row.createdAt,row.updatedAt]); for (const row of (db.organizationResources || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_resources(id,organization_id,title,description,url,kind,visibility,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,url=EXCLUDED.url,kind=EXCLUDED.kind,visibility=EXCLUDED.visibility,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.title,row.description||null,row.url||null,row.kind||null,row.visibility||'organization',row.createdBy,row.createdAt,row.updatedAt]); for (const row of (db.organizationReportSchedules || []).filter(x => x.organizationId === organizationId)) await client.query(`INSERT INTO organization_report_schedules(id,organization_id,report_type,frequency,recipients,filters,active,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET report_type=EXCLUDED.report_type,frequency=EXCLUDED.frequency,recipients=EXCLUDED.recipients,filters=EXCLUDED.filters,active=EXCLUDED.active,updated_at=EXCLUDED.updated_at`, [row.id,organizationId,row.reportType,row.frequency,j(row.recipients),j(row.filters),row.active!==false,row.createdBy,row.createdAt,row.updatedAt]); await client.query('COMMIT'); return { enabled: true } } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } }
export async function syncOrganizationCommercial(organizationId = null) {
  if (!writeEnabled()) return { enabled: false }
  const db = readAuthorityDb()
  const client = await getPool().connect()
  const scoped = name => (db[name] || []).filter(row => !organizationId || row.organizationId === organizationId)
  const timestamp = value => value || new Date().toISOString()
  try {
    await client.query('BEGIN')
    for (const row of scoped('organizationEntitlements')) await client.query(`INSERT INTO organization_entitlements(id,organization_id,plan,source,status,capabilities,limits,starts_at,expires_at,payment_intent_id,provider_reference,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(id) DO UPDATE SET plan=EXCLUDED.plan,source=EXCLUDED.source,status=EXCLUDED.status,capabilities=EXCLUDED.capabilities,limits=EXCLUDED.limits,starts_at=EXCLUDED.starts_at,expires_at=EXCLUDED.expires_at,payment_intent_id=EXCLUDED.payment_intent_id,provider_reference=EXCLUDED.provider_reference,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId,row.plan,row.source,row.status,j(row.capabilities),j(row.limits),row.startsAt||null,row.expiresAt||null,row.paymentIntentId||null,row.providerReference||null,row.createdBy||null,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('organizationBudgets')) await client.query(`INSERT INTO organization_budgets(id,organization_id,program_id,hackathon_id,source,status,balance,reserved_balance,currency,expires_at,payment_intent_id,provider_reference,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,balance=EXCLUDED.balance,reserved_balance=EXCLUDED.reserved_balance,expires_at=EXCLUDED.expires_at,payment_intent_id=EXCLUDED.payment_intent_id,provider_reference=EXCLUDED.provider_reference,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId,row.programId||null,row.hackathonId||null,row.source,row.status,row.balance,row.reservedBalance||0,row.currency||'credits',row.expiresAt||null,row.paymentIntentId||null,row.providerReference||null,row.createdBy||null,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('organizationUsage')) await client.query(`INSERT INTO organization_usage(id,request_id,organization_id,budget_id,program_id,hackathon_id,credits,settled_credits,released_credits,status,metadata,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(request_id) DO UPDATE SET settled_credits=EXCLUDED.settled_credits,released_credits=EXCLUDED.released_credits,status=EXCLUDED.status,metadata=EXCLUDED.metadata,updated_at=EXCLUDED.updated_at`, [row.id,row.requestId,row.organizationId,row.budgetId,row.programId||null,row.hackathonId||null,row.credits,row.settledCredits||0,row.releasedCredits||0,row.status,j(row.metadata),timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('organizationSponsorshipPackages')) await client.query(`INSERT INTO organization_sponsorship_packages(id,organization_id,name,description,package_type,amount,currency,benefits,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,package_type=EXCLUDED.package_type,amount=EXCLUDED.amount,currency=EXCLUDED.currency,benefits=EXCLUDED.benefits,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId,row.name,row.description||null,row.packageType,row.amount,row.currency||null,j(row.benefits),row.status,row.createdBy,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('sponsorshipApplications')) await client.query(`INSERT INTO sponsorship_applications(id,organization_id,package_id,sponsor_name,sponsor_contact,requested_benefits,status,reviewed_by,reviewed_at,rejection_reason,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,reviewed_by=EXCLUDED.reviewed_by,reviewed_at=EXCLUDED.reviewed_at,rejection_reason=EXCLUDED.rejection_reason,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId,row.packageId,row.sponsorName,j(row.sponsorContact),j(row.requestedBenefits),row.status,row.reviewedBy||null,row.reviewedAt||null,row.rejectionReason||null,row.createdBy,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('sponsorshipTransactions')) await client.query(`INSERT INTO sponsorship_transactions(id,application_id,organization_id,payment_intent_id,provider,provider_reference,amount,currency,credits,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET payment_intent_id=EXCLUDED.payment_intent_id,provider=EXCLUDED.provider,provider_reference=EXCLUDED.provider_reference,amount=EXCLUDED.amount,currency=EXCLUDED.currency,credits=EXCLUDED.credits,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at`, [row.id,row.applicationId,row.organizationId,row.paymentIntentId||null,row.provider||null,row.providerReference||null,row.amount||0,row.currency||null,row.credits||0,row.status||'pending',timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('sponsorshipBenefits')) await client.query(`INSERT INTO sponsorship_benefits(id,transaction_id,organization_id,benefit_type,description,status,consent_required,fulfilled_by,fulfilled_at,metadata,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,consent_required=EXCLUDED.consent_required,fulfilled_by=EXCLUDED.fulfilled_by,fulfilled_at=EXCLUDED.fulfilled_at,metadata=EXCLUDED.metadata,updated_at=EXCLUDED.updated_at`, [row.id,row.transactionId,row.organizationId,row.benefitType,row.description||null,row.status||'pending',row.consentRequired===true,row.fulfilledBy||null,row.fulfilledAt||null,j(row.metadata),timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('startupCandidates')) await client.query(`INSERT INTO startup_candidates(id,organization_id,hackathon_id,team_id,founder_id,name,status,consent_at,consent_version,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,status=EXCLUDED.status,consent_at=EXCLUDED.consent_at,consent_version=EXCLUDED.consent_version,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId||null,row.hackathonId||null,row.teamId||null,row.founderId,row.name,row.status,row.consentAt,row.consentVersion,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('managedHackathonOperations')) await client.query(`INSERT INTO managed_hackathon_operations(id,organization_id,hackathon_id,service_tier,status,checklist,sla,assigned_team,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET service_tier=EXCLUDED.service_tier,status=EXCLUDED.status,checklist=EXCLUDED.checklist,sla=EXCLUDED.sla,assigned_team=EXCLUDED.assigned_team,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId,row.hackathonId||null,row.serviceTier,row.status,j(row.checklist),j(row.sla),row.assignedTeam||null,row.createdBy,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('organizationInstitutionalSettings')) await client.query(`INSERT INTO organization_institutional_settings(id,organization_id,white_label,integrations,sla,support,updated_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(organization_id) DO UPDATE SET white_label=EXCLUDED.white_label,integrations=EXCLUDED.integrations,sla=EXCLUDED.sla,support=EXCLUDED.support,updated_by=EXCLUDED.updated_by,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId,j(row.whiteLabel),j(row.integrations),j(row.sla),j(row.support),row.updatedBy||null,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('organizationAbuseReviews')) await client.query(`INSERT INTO organization_abuse_reviews(id,organization_id,user_id,hackathon_id,signal_type,score,status,evidence,reviewed_by,reviewed_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(id) DO UPDATE SET score=EXCLUDED.score,status=EXCLUDED.status,evidence=EXCLUDED.evidence,reviewed_by=EXCLUDED.reviewed_by,reviewed_at=EXCLUDED.reviewed_at,updated_at=EXCLUDED.updated_at`, [row.id,row.organizationId||null,row.userId||null,row.hackathonId||null,row.signalType,row.score||0,row.status||'open',j(row.evidence),row.reviewedBy||null,row.reviewedAt||null,timestamp(row.createdAt),timestamp(row.updatedAt)])
    for (const row of scoped('organizationBillingEvents')) await client.query(`INSERT INTO organization_billing_events(id,organization_id,payment_intent_id,purchase_type,provider,provider_reference,amount,currency,credits,plan_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO NOTHING`, [row.id,row.organizationId,row.paymentIntentId||null,row.purchaseType,row.provider||null,row.providerReference||null,row.amount||0,row.currency||null,row.credits||0,row.planId||null,timestamp(row.createdAt)])
    await client.query('COMMIT')
    return { enabled: true, entitlements: scoped('organizationEntitlements').length, budgets: scoped('organizationBudgets').length, usage: scoped('organizationUsage').length, packages: scoped('organizationSponsorshipPackages').length, applications: scoped('sponsorshipApplications').length, transactions: scoped('sponsorshipTransactions').length, benefits: scoped('sponsorshipBenefits').length, candidates: scoped('startupCandidates').length, managedOperations: scoped('managedHackathonOperations').length, institutionalSettings: scoped('organizationInstitutionalSettings').length, abuseReviews: scoped('organizationAbuseReviews').length, billingEvents: scoped('organizationBillingEvents').length }
  } catch (error) {
    await client.query('ROLLBACK')
    throw error
  } finally {
    client.release()
  }
}
export function organizationReadEnabled() { return readEnabled() }
export function organizationWriteEnabled() { return writeEnabled() }
export function organizationFallbackEnabled(kind) { return fallback(kind) }
export async function closeOrganizationOperationsRepository() { await closePlatformPool() }
