import { Router } from 'express'
import { requireAuth } from '../middlewares/auth.js'
import { actionCreate, actionPatch, actions, activity, alumniOutcomes, auditEvents, auditVerify, briefing, briefingEvidence, cohortBenchmarks, cohortCreate, cohorts, kpiSave, kpis, memberPatch, members, overview, partnerCreate, partners, programHealth, pulse, recommendations, refresh, reportGenerate, reportScheduleCreate, reportSchedules, resourceAllocation, resourceCreate, resources, risks, startups } from '../controllers/organizationIntelligenceController.js'

const router = Router()
router.use(requireAuth)
router.get('/overview', overview)
router.get('/pulse', pulse)
router.get('/risks', risks)
router.get('/actions', actions)
router.post('/actions', actionCreate)
router.patch('/actions/:actionId', actionPatch)
router.get('/kpis', kpis)
router.post('/kpis', kpiSave)
router.get('/audit/integrity', auditVerify)
router.get('/briefing/evidence', briefingEvidence)
router.post('/briefing', briefing)
router.post('/refresh', refresh)
router.get('/recommendations', recommendations)
router.get('/activity', activity)
router.get('/members', members)
router.patch('/members/:memberId', memberPatch)
router.get('/cohorts', cohorts)
router.post('/cohorts', cohortCreate)
router.get('/partners', partners)
router.post('/partners', partnerCreate)
router.get('/resources', resources)
router.post('/resources', resourceCreate)
router.get('/report-schedules', reportSchedules)
router.post('/report-schedules', reportScheduleCreate)
router.get('/audit/events', auditEvents)
router.get('/startups', startups)
router.get('/programs/:programId/health', programHealth)
router.post('/reports/generate', reportGenerate)
router.get('/resource-allocation', resourceAllocation)
router.get('/alumni', alumniOutcomes)
router.get('/cohort-benchmarks', cohortBenchmarks)
export default router
