import type { Hackathon, Program, Funding, Event, Opportunity } from "./types";
import { mentorshipRoomsAsOpportunities } from "../mentorship/data";

const TECHIT = { id: "org_techit", name: "TechIT Foundation", logoEmoji: "🌐" };
const GOOGLE = { id: "org_google", name: "Google for Startups", logoEmoji: "🟦" };
const FLUTTERWAVE = { id: "org_flutterwave", name: "Flutterwave", logoEmoji: "💸" };
const WHO_AFRICA = { id: "org_who", name: "WHO Africa", logoEmoji: "🩺" };
const TECHSTARS = { id: "org_techstars", name: "TechStars", logoEmoji: "⭐" };
const FELLOWSHIP = { id: "org_abf", name: "African Builders Fellowship", logoEmoji: "🪴" };
const SEQUOIA = { id: "org_sequoia", name: "Sequoia Spark", logoEmoji: "🌲" };
const MTN = { id: "org_mtn", name: "MTN Y'ello", logoEmoji: "📡" };
const VISA = { id: "org_visa", name: "Visa", logoEmoji: "💳" };
const SOLVE = { id: "org_solve", name: "MIT Solve", logoEmoji: "🧪" };
const YC = { id: "org_yc", name: "Y Combinator", logoEmoji: "🟧" };
const STRIPE = { id: "org_stripe", name: "Stripe", logoEmoji: "💼" };

export const HACKATHONS: Hackathon[] = [
  {
    id: "ai-for-africa-2026",
    type: "hackathon",
    title: "AI for Africa 2026",
    organizer: TECHIT,
    poster: "🤖",
    summary: "Build AI agents that solve a real African problem in 48 hours.",
    status: "open",
    applyDeadline: "2026-06-10",
    publishedAt: "2026-04-20",
    tags: ["AI", "Africa", "Agents"],
    featured: true,
    theme: "AI agents that solve a real African problem",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    durationHours: 48,
    prizePool: "$50,000",
    partners: ["TechIT", "Google for Startups", "Lagos Innovation Hub"],
    registrants: 420,
    teamsFormed: 87,
    hackathonStatus: "upcoming",
  },
  {
    id: "climate-builders-q2",
    type: "hackathon",
    title: "Climate Builders Q2",
    organizer: TECHIT,
    poster: "🌱",
    summary: "Carbon, water, and agriculture in emerging markets.",
    status: "open",
    applyDeadline: "2026-05-20",
    publishedAt: "2026-03-30",
    tags: ["Climate", "AgriTech"],
    theme: "Carbon, water, and agriculture in emerging markets",
    startDate: "2026-05-22",
    endDate: "2026-05-24",
    durationHours: 48,
    prizePool: "$30,000",
    partners: ["TechIT", "GreenTech Foundation"],
    registrants: 280,
    teamsFormed: 62,
    hackathonStatus: "live",
  },
  {
    id: "fintech-fast-track",
    type: "hackathon",
    title: "FinTech Fast Track",
    organizer: FLUTTERWAVE,
    poster: "💸",
    summary: "Cross-border payments for SMEs.",
    status: "closed",
    applyDeadline: "2026-04-08",
    publishedAt: "2026-02-15",
    tags: ["FinTech", "Payments"],
    theme: "Cross-border payments for SMEs",
    startDate: "2026-04-10",
    endDate: "2026-04-12",
    durationHours: 48,
    prizePool: "$40,000",
    partners: ["Flutterwave", "TechIT"],
    registrants: 312,
    teamsFormed: 71,
    hackathonStatus: "judging",
  },
  {
    id: "healthx-spring",
    type: "hackathon",
    title: "HealthX Spring",
    organizer: WHO_AFRICA,
    poster: "🩺",
    summary: "Telemedicine for rural clinics.",
    status: "closed",
    applyDeadline: "2026-02-12",
    publishedAt: "2026-01-05",
    tags: ["HealthTech", "Telemedicine"],
    theme: "Telemedicine for rural clinics",
    startDate: "2026-02-14",
    endDate: "2026-02-16",
    durationHours: 48,
    prizePool: "$25,000",
    partners: ["WHO Africa", "TechIT"],
    registrants: 198,
    teamsFormed: 44,
    hackathonStatus: "completed",
  },
];

export const PROGRAMS: Program[] = [
  {
    id: "techstars-tools-2026",
    type: "program",
    title: "TechStars Tools Cohort 24",
    organizer: TECHSTARS,
    poster: "⭐",
    summary: "12-week accelerator for B2B SaaS founders. $25k stipend + mentorship.",
    status: "closing-soon",
    applyDeadline: "2026-06-01",
    publishedAt: "2026-04-01",
    tags: ["B2B", "SaaS", "Accelerator"],
    featured: true,
    format: "accelerator",
    durationWeeks: 12,
    cohortSize: 12,
    perks: ["$25k stipend", "Office space (London)", "Demo Day", "1:1 mentor"],
    startDate: "2026-07-01",
  },
  {
    id: "african-builders-fellowship",
    type: "program",
    title: "African Builders Fellowship",
    organizer: FELLOWSHIP,
    poster: "🪴",
    summary: "6-month incubator for early-stage African founders.",
    status: "open",
    applyDeadline: "2026-08-30",
    publishedAt: "2026-05-01",
    tags: ["Incubator", "Africa", "Pre-seed"],
    format: "incubator",
    durationWeeks: 26,
    cohortSize: 20,
    perks: ["$10k grant", "Weekly mentor circles", "Investor intros"],
    startDate: "2026-09-15",
  },
  {
    id: "sequoia-spark-mentorship",
    type: "program",
    title: "Sequoia Spark Mentorship",
    organizer: SEQUOIA,
    poster: "🌲",
    summary: "3-month 1:1 mentorship from Sequoia partners. Application-only.",
    status: "open",
    applyDeadline: "2026-07-15",
    publishedAt: "2026-05-12",
    tags: ["Mentorship", "Seed"],
    format: "mentorship",
    durationWeeks: 12,
    cohortSize: 30,
    perks: ["1:1 monthly with a Sequoia partner", "Founder retreat"],
    startDate: "2026-08-01",
  },
];

export const FUNDING: Funding[] = [
  {
    id: "google-cloud-credits-africa",
    type: "funding",
    title: "Google for Startups Africa Cloud Credits",
    organizer: GOOGLE,
    poster: "🟦",
    summary: "Up to $100k in Google Cloud credits for African startups.",
    status: "open",
    applyDeadline: "2026-09-01",
    publishedAt: "2026-04-15",
    tags: ["Cloud", "Credits", "Africa"],
    format: "grant",
    amountRange: "$10k – $100k",
    equityRequired: false,
    audienceStage: ["MVP", "Beta", "Launch"],
  },
  {
    id: "mtn-yello-pilot-rfp",
    type: "funding",
    title: "MTN Y'ello Pilot RFP",
    organizer: MTN,
    poster: "📡",
    summary: "Pilot opportunity for telco-adjacent startups across Africa.",
    status: "closing-soon",
    applyDeadline: "2026-05-31",
    publishedAt: "2026-04-20",
    tags: ["Telco", "Pilot", "Africa"],
    format: "pilot",
    amountRange: "Pilot contract",
    equityRequired: false,
    audienceStage: ["Beta", "Launch", "Growth"],
  },
  {
    id: "visa-fintech-fast-track-grant",
    type: "funding",
    title: "Visa FinTech Fast-Track Grant",
    organizer: VISA,
    poster: "💳",
    summary: "Non-dilutive grant + Visa network access for FinTech founders.",
    status: "open",
    applyDeadline: "2026-08-15",
    publishedAt: "2026-05-05",
    tags: ["FinTech", "Grant"],
    format: "grant",
    amountRange: "$50k – $250k",
    equityRequired: false,
    audienceStage: ["Beta", "Launch"],
  },
  {
    id: "mit-solve-climate",
    type: "funding",
    title: "MIT Solve Climate Challenge",
    organizer: SOLVE,
    poster: "🧪",
    summary: "Equity-light funding for climate-tech ventures with MIT mentorship.",
    status: "open",
    applyDeadline: "2026-07-30",
    publishedAt: "2026-05-10",
    tags: ["Climate", "Research"],
    format: "grant",
    amountRange: "$100k – $500k",
    equityRequired: true,
    audienceStage: ["Idea", "MVP", "Beta"],
  },
];

export const EVENTS: Event[] = [
  {
    id: "yc-demo-day-watch-party",
    type: "event",
    title: "YC Demo Day Watch Party",
    organizer: YC,
    poster: "🟧",
    summary: "Watch the latest YC batch demo and network with Lagos founders.",
    status: "open",
    applyDeadline: "2026-06-04",
    publishedAt: "2026-05-15",
    tags: ["Networking", "YC"],
    format: "demo-day",
    startDate: "2026-06-05T15:00:00Z",
    durationMinutes: 180,
    hostedBy: "TechIT Lagos",
    isVirtual: false,
  },
  {
    id: "lagos-founder-ama-iyin",
    type: "event",
    title: "Founder AMA with Iyin Aboyeji",
    organizer: TECHIT,
    poster: "🎙",
    summary: "Live Q&A with Future Africa's founding partner.",
    status: "open",
    applyDeadline: "2026-06-09",
    publishedAt: "2026-05-18",
    tags: ["AMA", "Africa"],
    format: "ama",
    startDate: "2026-06-10T17:00:00Z",
    durationMinutes: 90,
    hostedBy: "TechIT Foundation",
    isVirtual: true,
  },
  {
    id: "stripe-atlas-workshop",
    type: "event",
    title: "Stripe Atlas Workshop: Incorporate from Anywhere",
    organizer: STRIPE,
    poster: "💼",
    summary: "Hands-on session: incorporate a Delaware C-corp via Stripe Atlas.",
    status: "open",
    applyDeadline: "2026-06-19",
    publishedAt: "2026-05-20",
    tags: ["Workshop", "Legal"],
    format: "workshop",
    startDate: "2026-06-20T14:00:00Z",
    durationMinutes: 120,
    hostedBy: "Stripe",
    isVirtual: true,
  },
];

// Investor mentorship rooms surface here as announcements (type "program",
// format "mentorship") — derived so adding a room auto-publishes it.
export const OPPORTUNITIES: Opportunity[] = [
  ...HACKATHONS,
  ...PROGRAMS,
  ...mentorshipRoomsAsOpportunities(),
  ...FUNDING,
  ...EVENTS,
];

export function findOpportunity(id: string): Opportunity | undefined {
  return OPPORTUNITIES.find((o) => o.id === id);
}

export function findHackathon(id: string): Hackathon | undefined {
  return HACKATHONS.find((h) => h.id === id);
}
